- type: generative
  method_name: ciagan
  description: 'CIAGAN (weight: 0.5)'
  weights_path: ./weight/ciagan_pre_trained/modelG_ciagan.pth
  retinaface_model: ./weight/retinaface_pre_trained/Resnet50_Final.pth
  dlib_path: ./weight/ciagan_pre_trained/shape_predictor_68_face_landmarks.dat
- type: generative
  method_name: deid_rppg
  description: 'DeID-rPPG (weight: 0.5)'
  weights_path: ./weight/deid_rppg_pre_trained/autoencoder.pt
